name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5.2
        with:
          image: ghcr.io/will-scargill/echo
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
